### ISSUE TITLE
NoneType Error

### ISSUE THREAD

**Issue by caday00** [adamcrosby/xccdf2tsv#1]
Receiving an `AttributeError: 'NoneType' object has no attribute 'text'` error, on line 56 

check = group.find("{%s}Rule/{%s}check/{%s}check-content" % (xmlns, xmlns, xmlns)).text

**Comment by adamcrosby** [comment]
Which XCCDF file are you using that generates this error?

**Comment by caday00** [comment]
U_Windows_7_V1R19_STIG_Benchmark > TestLaptop_XCCDF-Results_U_Windows_7_V1R19_STIG_Benchmark

**Comment by adamcrosby** [comment]
While I take a look at the bug, you can get the CSV here (click 'excel' in the top right section):
http://www.stigviewer.com/stig/windows_7/

**Comment by adamcrosby** [comment]
FYI, the issue appears to be related to using OVAL SCAP benchmarks instead of the 'Manual-XCCDF.xml' files.  The Manual files have a 

``` xml
<check><check-content>Manual Check Stuff</check-content></check> 
```

while the OVAL benchmarks only point to a 

``` xml
<check><check-content-ref>URI</check-content-ref></check> 
```

set of elements (referencing a OVAL URI).

I've added an exception handler around this element in the script so it won't blow up, but if you actually want that content, you'll need to grab the 'manual' benchmark file.
